# Generated by Django 5.2.8 on 2025-12-14 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0002_residentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=120, unique=True)),
                ('guest_name', models.CharField(max_length=120)),
                ('reason', models.CharField(max_length=120)),
                ('valid_until', models.DateField()),
                ('aditional_information', models.TextField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.residence')),
            ],
        ),
    ]
