# Generated by Django 5.2.8 on 2025-12-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_invitation_aditional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='valid_until',
            field=models.DateTimeField(),
        ),
    ]
